## Introduction

The purpose of this assignment is to explain the numpy.raddom package

Raqndom number are a core part of Data Analysis, however there is really no such thing as a truly random number in the computing 
general world. In this assignment I will attempt to show some of the techniques to generate "psudo" random numbers using the 
Python  programming language [3] and its inbuilt package numpy.random [4] and its subroutines.

Typically when not using excel, you could use these packages to generate more accurate numbers for large data, and shape it in to multi dimensional arrays.

We will look at the standard simple random functions, then some "Distributions", and finally the use of "seeds"

First we will import the package:

## References 
### [1] Scipy reference on random routines 
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html
### [2] Interesting document on random number generation incl seeding
https://pdfs.semanticscholar.org/6d7f/5255b1fc569eb96d91f66ac824d18e115e72.pdf
### [3] Pythom home page
http.python.org'
### [4] Numpy home page
http://numpy.org/

### [5] Pseudorandom numbers
https://en.wikipedia.org/wiki/Random_seed
https://en.wikipedia.org/wiki/Random_seed

### [6] Normal distribution
https://en.wikipedia.org/wiki/Normal_distribution
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.normal.html#numpy.random.normal

### [7] Raleigh distribution
http://www.brighton-webs.co.uk/distributions/rayleigh.asp


In [1]:
import numpy.random

### Simple random data functons (standard definitions ref #1.)

rand(d0, d1, ..., dn) 	Random values in a given shape.simple distrubiton over a given array of numbers

randn(d0, d1, ..., dn) 	Return a sample (or samples) from the “standard normal” distribution.

randint(low[, high, size, dtype]) 	Return random integers from low (inclusive) to high (exclusive).

random_integers(low[, high, size]) 	Random integers of type np.int between low and high, inclusive.

random_sample([size]) 	Return random floats in the half-open interval [0.0, 1.0).

random([size]) 	Return random floats in the half-open interval [0.0, 1.0).

ranf([size]) 	Return random floats in the half-open interval [0.0, 1.0).

sample([size]) 	Return random floats in the half-open interval [0.0, 1.0).

choice(a[, size, replace, p]) 	Generates a random sample from a given 1-D array

bytes(length) 	Return random bytes.  

Most of the functions below would be used for accountancy functions,
or big data manipulation.


### numpy.rand without and with arguments, multi dimensional array

In [2]:
numpy.random.rand()

0.4250144812035854

In [3]:
numpy.random.rand(2,3)

array([[ 0.12235862,  0.60492237,  0.05187935],
       [ 0.80004535,  0.81269963,  0.92904232]])

### numpy.randn No args, with args
Return a sample (or samples) from the “standard normal” distribution.

In [4]:
numpy.random.randn()

-0.9399875379529219

With args Returns:	

Z : ndarray or float

    A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, 
    or a single such float if no parameters were supplied.
"Andrew.. to be honest I do not understand the difference from above..."

In [5]:
2.5 * numpy.random.randn(2, 4) + 3

array([[-2.5902101 ,  3.47098089,  4.06591128,  2.93444516],
       [ 1.83516222, -0.07206408,  1.76307733,  2.0192402 ]])

## numpy.randint
(low[, high, size, dtype]) 	Return random integers from low (inclusive) to high (exclusive).
Can give an array of randoms, single dimensional, between two numbers or multi dimensional


In [6]:
numpy.random.randint(5, size=10)

array([0, 1, 1, 2, 3, 3, 4, 2, 3, 4])

In [7]:
numpy.random.randint(5, size=(3, 4))

array([[2, 4, 1, 0],
       [3, 0, 0, 0],
       [4, 0, 3, 4]])

## numpy.random_integers(low, high, size) 
Random integers of type int between low and high, inclusive.
Either one dimensional or multi dimensional array
Note size is indexed from 0.. random_integers was replaced by randit... 

In [8]:
numpy.random.randint(1, 5 +1)

3

## numpy.random_sample([size]) 	
Return random floats in the half-open interval [0.0, 1.0).
Caqn be passed 0 args for 1 number, a list (2 args) or an array shape.
Can be passed arg for type, and negative numbers

In [9]:
numpy.random.random_sample()

0.6504027051776178

In [10]:
numpy.random.random_sample((4,))

array([ 0.21429499,  0.25297042,  0.23896947,  0.4855855 ])

## numpy.random([size]) Return random floats in the half-open interval [0.0, 1.0).
Basic random function. Returns an array of ints/floats, can be single, a list or a multidimentional array

In [11]:
numpy.random.random_sample()


0.5483393821084896

## numpy.random.ranf Return random floats in the half-open interval [0.0, 1.0)

In [12]:
(b - a) * random_sample() + a
Array of random floats of shape size (unless size=None, in which case a single float is returned).

SyntaxError: invalid syntax (<ipython-input-12-6c43a7a5835d>, line 2)

## sample([size]) Return random floats in the half-open interval [0.0, 1.0).

In [ ]:
Return random floats in the half-open interval [0.0, 1.0).

## choice(a[, size, replace, p]) Generates a random sample from a given 1-D array

In [ ]:
Generates a random sample from a given 1-D array

## bytes(length) Return random bytes.

In [ ]:
    Return random bytes.
    Parameters:	

    length : int

        Number of random bytes.

    Returns:	

    out : str

        String of length length.

    Examples

    >>> np.random.bytes(10)
    ' eh\x85\x022SZ\xbf\xa4' #random



## Permutations

Two little fairly basic libs dont really do much, just shuffle stuff around.

shuffle(x) 	Modify a sequence in-place by shuffling its contents.

permutation(x) 	Randomly permute a sequence, or return a permuted range.

### numpy.random.shuffle
This function only shuffles the array along the first axis of a multi-dimensional array. 
The order of sub-arrays is changed but their contents remains the same.  Could be useful for
"mixing up known data" like employee numbers etc... 

In [ ]:
arr = numpy.arange(10)
numpy.random.shuffle(arr)
arr

### Permutation(n.nnn) 
Randomly permute a sequence, or return a permuted range.  Can be a list or a multi dimensional array
Actually this one would be better for above scenario, if you can pass in a list by pointer.

In [ ]:
numpy.random.permutation([1, 6, 3, 12, 15])

## Distributions

## normal([loc, scale, size]) 	Draw random samples from a normal (Gaussian) distribution.



In [ ]:
This is used to demonstrate what they call "Normal Distribution" Ref [6], or very commonly 
a bell curve, where some factors and influences will make a peak curve then tail off.. tail off, typically with
a big input, factors will peak, and then tail off.

<img src ="nrq.png">



## pareto(a[, size]) 	Draw samples from a Pareto II or Lomax distribution with specified shape [Ref 6]Wikipedia
"The 80/20 rule"

The Pareto distribution, named after the Italian civil engineer, economist, and sociologist Vilfredo Pareto, 
is a power-law probability distribution that is used in description of social, scientific, geophysical, 
actuarial, and many other types of observable phenomena. 
Originally applied to describing the distribution of wealth in a society, fitting the trend that a large
portion of wealth is held by a small fraction of the population, 
the Pareto distribution has colloquially become known and referred to as the Pareto principle, 
or "80-20 rule", and is sometimes called the "Matthew principle". 
This rule states that, for example, 80% of the wealth of a society is held by 20% of its population. 
However, the Pareto distribution only produces this result for a particular power value, 


## poisson([lam, size]) 	.  A probability theory, given over a space of time

(Wikipedia [6]) For instance, an individual keeping track of the amount of mail they receive each 
day may notice that they receive an average number of 4 letters per day. 
If receiving any particular piece of mail does not affect the arrival times of future pieces of mail, 
i.e., if pieces of mail from a wide range of sources arrive independently of one another, 
then a reasonable assumption is that the number of pieces of mail received in a day obeys a Poisson distribution.

Other examples that may follow a Poisson include the number of phone calls received by a call center per hour 
and the number of decay events per second from a radioactive source. 

power(a[, size]) 	Draws samples in [0, 1] from a power distribution with positive exponent a - 

The power function distribution is just the inverse of the Pareto distribution. It may also be seen as a special case of the Beta distribution.

It is used, for example, in modeling the over-reporting of insurance claims. (Wikipedia [6])

In [ ]:
rayleigh([scale, size]) 	Draw samples from a Rayleigh distribution.

Used for gale force measurment.


The Rayleigh distribution would arise, for example, if the East and North components of the wind velocity had identical 
zero-mean Gaussian ( see normal distribution above.. ) distributions. 
Then the wind speed would have a Rayleigh distribution.
Ref [7] 

## Number generators

### seed([seed]) 	Seed the generator.



It is used, for example, in modeling the over-reporting of insurance claims.
Reference [5]Wikipedia
A random seed (or seed state, or just seed) is a number (or vector) used to initialize a pseudorandom number generator.

For a seed to be used in a pseudorandom number generator, it does not need to be random. 
Because of the nature of number generating algorithms, so long as the original seed is ignored, 
the rest of the values that the algorithm generates will follow probability distribution in a pseudorandom manner.
The choice of a good random seed is crucial in the field of computer security. 
When a secret encryption key is pseudorandomly generated, having the seed will allow one to obtain the key. 
High entropy is important for selecting good random seed data.[1]
If the same random seed is deliberately shared, it becomes a secret key, so two or more systems 
using matching pseudorandom number algorithms 
and matching seeds can generate matching sequences of non-repeating 
numbers which can be used to synchronize remote systems, such as GPS satellites and receivers.
Random seeds are often generated from the state of the computer system (such as the time), 
a cryptographically secure pseudorandom number generator or from a hardware random number generation.

